# Generated by Django 4.2.30 on 2026-04-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShellTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shell_type', models.CharField(choices=[('reverse', 'Reverse Shell'), ('bind', 'Bind Shell')], max_length=20)),
                ('language', models.CharField(choices=[('bash', 'Bash'), ('python', 'Python'), ('php', 'PHP'), ('powershell', 'PowerShell'), ('netcat', 'Netcat')], max_length=20)),
                ('os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('any', 'Any')], default='any', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('template', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['shell_type', 'language', 'name'],
            },
        ),
    ]
