# Generated by Django 4.2.30 on 2026-04-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NmapProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scan_type', models.CharField(max_length=50)),
                ('nse_categories', models.CharField(blank=True, max_length=200)),
                ('extra_flags', models.CharField(blank=True, max_length=300)),
                ('noise_level', models.CharField(default='low', max_length=20)),
                ('lab_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
