# Generated by Django 4.2.30 on 2026-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('platform', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField()),
                ('prerequisites', models.TextField(blank=True)),
                ('commands', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['platform', 'category', 'title'],
            },
        ),
    ]
