# Generated by Django 4.2.30 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playbooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbookentry",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]

